### ISSUE TITLE
線上電子書尚未更新

### ISSUE THREAD

**Issue by goodjack** [SLMT/google-cpp-style-guide-zh-tw#5]
感謝持續更新翻譯 Google C++ Style Guide！

剛發現這裡有比較新的翻譯內容
看起來線上電子書還沒有更新
再麻煩請你更新 謝謝你的持續貢獻 👏👏

**Comment by SLMT** [comment]
Hi~ 感謝你的回報！
我晚點檢查一下是甚麼問題~

**Comment by SLMT** [comment]
@goodjack 電子書更新囉~ 不過我發現只有 README 沒有更新到而已~ 其實其他內容都已經是最新的了。抱歉我翻譯得很慢@@
